version: "3.5"
services:
  gaboot-cms-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gaboot-cms-frontend-container
    restart: unless-stopped
    init: true
    ports:
      - 8002:81
      # - 8443:443
